spring:
  application:
    name: auth-app-backend
  profiles:
    active: dev
server:
  port: 8082

#configurations
#database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app_db?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
